[main]
file_path = "../private/default.xex"
out_directory_path = "../ppc"
switch_table_file_path = "EOTJumpTable.toml"

skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x8233e480
savegprlr_14_address = 0x8233e430
restfpr_14_address = 0x8233FA4C
savefpr_14_address = 0x8233fA00
restvmx_14_address = 0x8233f768
savevmx_14_address = 0x8233f4d0
restvmx_64_address = 0x8233f7fc
savevmx_64_address = 0x8233f564

functions = [
    { address = 0x821160a8, size = 0x198 },
    { address = 0x821bebd0, size = 0x118 },
    { address = 0x821c09f0, size = 0x98 },
    { address = 0x821c0a88, size = 0x9C },
    { address = 0x82339f68, size = 0x2E4 },
    { address = 0x8235dd58, size = 0x4DC },
    { address = 0x82368ef0, size = 0x4EC },
    { address = 0x82375bf0, size = 0x980 },
    { address = 0x82378450, size = 0xEC },
]